# 分支保护规则
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "build"
          - "test"
          - "lighthouse"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions:
        users: []
        teams: []
      allow_force_pushes: false
      allow_deletions: false

  - name: gh-pages
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "build"
          - "test"
          - "lighthouse"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions:
        users: []
        teams: []
      allow_force_pushes: false
      allow_deletions: false

# 标签保护规则
tags:
  - pattern: "v*"
    protection:
      enforce_admins: true
      allow_force_pushes: false
      allow_deletions: false 