name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Debug git status
      run: |
        git status
        git remote -v
        git branch -a
    - name: Set up git remote
      run: |
        git remote set-url origin https://github.com/${{ github.repository }}.git
    
    - name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Kill process on 4173 (if any)
      run: |
        if lsof -i:4173; then
          lsof -ti:4173 | xargs kill -9
        fi
    - name: Start Vite Preview
      run: npm run preview -- --port 4173 &
    - name: Wait for preview
      run: npx wait-on http://localhost:4173/luxejapan-public/
    
    - name: Run Lighthouse CI
      run: npm run lhci:ci
    
    - name: Upload test results (ignore if not found)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
        if-no-files-found: ignore

    - name: Build
      run: npm run build
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist 